DROP TABLE IF EXISTS Measurement_Current;

CREATE TABLE Measurement_Current
(
    ID      int                 generated by default as identity,
    TIME    DOUBLE PRECISION    NOT NULL,
    IA      DOUBLE PRECISION    NOT NULL,
    IB      DOUBLE PRECISION    NOT NULL,
    IC      DOUBLE PRECISION    NOT NULL,
    primary key (ID)
);